name: Test

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Lint markdown
        run: npm run lint:markdown

      - name: Type checks
        run: npm run type-check

      - name: Test Insomnia
        run: npm test -w packages/insomnia

      - name: Test Insomnia Testing
        run: npm test -w packages/insomnia-testing
